"""SceneFactory public API."""

from .factory import BuildResult, SceneFactory
from .asset_validator import AssetValidator, validate_asset, validate_usd
from .asset_pipeline import AssetNormalizer, CollisionProcessor
from .dataset import DatasetResult, inspect_dataset, reproduce_dataset, validate_dataset
from .external import (
    ENVELOPE_SOURCE_FORMAT,
    EXTERNAL_SCHEMA_VERSION,
    ExternalSceneDocument,
    ExternalSceneError,
    adapt_external_scene,
    external_scene_schema,
    load_external_scene,
    normalize_producer,
)
from .registry import AssetLoader, AssetMetadata, AssetRegistry
from .trajectory import DatasetError, Episode, EpisodeFrame, EpisodeRecorder, load_episode
from .models import ArticulationJoint, InteriorRegion, InteractionRegion, SemanticState
from .planning import (
    InteractionAction,
    InteractionPlan,
    InteractionPlanningResult,
    InteractionWorldState,
    PLAN_SCHEMA_VERSION,
    PLANNER_VERSION,
    SUPPORTED_ACTIONS,
    plan_interaction,
    replay_interaction_plan,
    synthesize_articulation_task,
    validate_interaction_plan,
    apply_symbolic_interaction_action,
)
from .execution import (
    EXECUTION_COMMAND_SCHEMA_VERSION,
    EXECUTION_TRACE_SCHEMA_VERSION,
    DryRunInteractionExecutor,
    ExecutionCommand,
    ExecutionError,
    ExecutionResult,
    ExecutionStepResult,
    ExecutionTrace,
    ExecutionTraceStep,
    ExecutionTraceValidationResult,
    ExecutorCapabilities,
    InteractionExecutor,
    command_id_for,
    execute_interaction_plan,
    validate_execution_trace,
    write_execution_trace_atomic,
)
from .conformance import (
    CONFORMANCE_SCHEMA_VERSION,
    CORE_CONFORMANCE_CASES,
    CORE_PROFILE,
    EXECUTOR_NAMES,
    ConformanceCaseResult,
    ConformanceError,
    ConformanceValidationResult,
    ExecutorConformanceReport,
    capability_sha256,
    create_executor,
    normalize_executor_capabilities,
    run_executor_conformance,
    validate_conformance_report,
    write_conformance_report_atomic,
)

__all__ = [
    "AssetLoader",
    "AssetMetadata",
    "AssetRegistry",
    "ArticulationJoint",
    "AssetNormalizer",
    "AssetValidator",
    "BuildResult",
    "CollisionProcessor",
    "DatasetResult",
    "ExternalSceneDocument",
    "ExternalSceneError",
    "ENVELOPE_SOURCE_FORMAT",
    "EXTERNAL_SCHEMA_VERSION",
    "SceneFactory",
    "InteractionRegion",
    "InteriorRegion",
    "SemanticState",
    "InteractionAction",
    "InteractionPlan",
    "InteractionPlanningResult",
    "InteractionWorldState",
    "PLAN_SCHEMA_VERSION",
    "PLANNER_VERSION",
    "SUPPORTED_ACTIONS",
    "adapt_external_scene",
    "external_scene_schema",
    "inspect_dataset",
    "load_external_scene",
    "normalize_producer",
    "plan_interaction",
    "replay_interaction_plan",
    "reproduce_dataset",
    "synthesize_articulation_task",
    "validate_asset",
    "validate_interaction_plan",
    "apply_symbolic_interaction_action",
    "validate_dataset",
    "validate_usd",
    "DatasetError",
    "Episode",
    "EpisodeFrame",
    "EpisodeRecorder",
    "load_episode",
    "EXECUTION_COMMAND_SCHEMA_VERSION",
    "EXECUTION_TRACE_SCHEMA_VERSION",
    "DryRunInteractionExecutor",
    "ExecutionCommand",
    "ExecutionError",
    "ExecutionResult",
    "ExecutionStepResult",
    "ExecutionTrace",
    "ExecutionTraceStep",
    "ExecutionTraceValidationResult",
    "ExecutorCapabilities",
    "InteractionExecutor",
    "command_id_for",
    "execute_interaction_plan",
    "validate_execution_trace",
    "write_execution_trace_atomic",
    "CONFORMANCE_SCHEMA_VERSION",
    "CORE_CONFORMANCE_CASES",
    "CORE_PROFILE",
    "EXECUTOR_NAMES",
    "ConformanceCaseResult",
    "ConformanceError",
    "ConformanceValidationResult",
    "ExecutorConformanceReport",
    "capability_sha256",
    "create_executor",
    "normalize_executor_capabilities",
    "run_executor_conformance",
    "validate_conformance_report",
    "write_conformance_report_atomic",
]
__version__ = "0.1.0"
